name: release

on:
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs:
  pdk:
    strategy:
      matrix:
        family: ['gf180mcu']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install volare
        run: |
          python -m venv env
          env/bin/python -m pip install -r requirements.txt
          env/bin/python -m pip install .

      - uses: actions/checkout@v3
        with:
          repository: 'The-OpenROAD-Project/OpenLane'
          ref: 'master'
          path: 'OpenLane'

      - uses: actions/checkout@v3
        with:
          repository: 'efabless/open_pdks'
          ref: 'master'
          path: 'open_pdks'

      - uses: actions/checkout@v3
        with:
          repository: 'google/gf180mcu-pdk'
          ref: 'main'
          path: 'gf180mcu-pdk'
          submodules: true

      - name: env
        run: |
          VOLARE_PATH=$(env/bin/volare path)
          PDK_FAMILY=${{ matrix.family }}
          echo "VOLARE_PATH=$VOLARE_PATH" >> $GITHUB_ENV
          echo "PDK_FAMILY=$PDK_FAMILY" >> $GITHUB_ENV
          OPEN_PDKS_DIR=$(readlink -f open_pdks)
          OPEN_PDKS_REV=$(cd $OPEN_PDKS_DIR && git rev-parse HEAD)
          OPEN_PDKS_DATE=$(cd $OPEN_PDKS_DIR && git log -1 --pretty=format:"%ad" --date=iso)
          FOUNDRY_PDK_DIR=$(readlink -f gf180mcu-pdk)
          FOUNDRY_PDK_REV=$(cd $FOUNDRY_PDK_DIR && git rev-parse HEAD)
          echo "OPEN_PDKS_DIR=$OPEN_PDKS_DIR" >> $GITHUB_ENV
          echo "OPEN_PDKS_REV=$OPEN_PDKS_REV" >> $GITHUB_ENV
          echo "OPEN_PDKS_DATE=$OPEN_PDKS_DATE" >> $GITHUB_ENV
          echo "FOUNDRY_PDK_DIR=$FOUNDRY_PDK_DIR" >> $GITHUB_ENV
          echo "FOUNDRY_PDK_REV=$FOUNDRY_PDK_REV" >> $GITHUB_ENV

      - name: cache build
        id: cache
        uses: actions/cache@v3
        env:
          CACHE_NUMBER: 0
        with:
          path: ${{ env.VOLARE_PATH }}/volare/${{ env.PDK_FAMILY}}/build/${{ env.OPEN_PDKS_REV}}
          key:
            ${{ runner.os }}-build-${{ env.CACHE_NUMBER }}-${{ env.OPEN_PDKS_REV }}-${{ env.FOUNDRY_PDK_REV }}

      - name: build
        run: |
          env/bin/volare build \
            --pdk ${{ matrix.family }} \
            --metadata-file=OpenLane/dependencies/tool_metadata.yml \
            --use-repo-at open_pdks=$OPEN_PDKS_DIR \
            --use-repo-at gf180mcu=$FOUNDRY_PDK_DIR
        if: steps.cache.outputs.cache-hit != 'true'

      - name: upload logs
        uses: actions/upload-artifact@v3
        with:
            name: ${{ matrix.family }}-build-logs
            path: |
              ${{ env.VOLARE_PATH }}/volare/logs/*/*.log
        if: always()

      - name: compress
        run: |
          tar -C $VOLARE_PATH/volare/$PDK_FAMILY/build/$OPEN_PDKS_REV/ \
              -cvJf default.tar.xz gf180mcuA/ gf180mcuB/ gf180mcuC/

      - name: upload archive
        uses: actions/upload-artifact@v3
        with:
            name: ${{ matrix.family }}-build-archive
            path: |
              default.tar.xz

      - uses: softprops/action-gh-release@v1
        with:
          name: ${{ matrix.family }}-${{ env.OPEN_PDKS_REV }}
          body: |
            ${{ env.PDK_FAMILY }} variants built using open_pdks ${{ env.OPEN_PDKS_REV }} (released on ${{ env.OPEN_PDKS_DATE }})
          files: |
            default.tar.xz
        if: startsWith(github.ref, 'refs/tags/')
